# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore DeptManagement.RazorPage/DeptManagement.RazorPage.csproj
RUN dotnet publish DeptManagement.RazorPage/DeptManagement.RazorPage.csproj -c Release -o /app --no-restore

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app .

EXPOSE 8080

ENTRYPOINT ["dotnet", "DeptManagement.RazorPage.dll"]
